---
output:
  html_document:
    code_folding: hide
params: 
  path: "/Users/ben_barnard/Box Sync/Graduate School/GradSchoolReport/Data"
---

```{r setup, message = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(GradSchoolReport)
library(ggplot2)
library(knitr)
library(tidyr)
library(dplyr)
```

```{r data}
enrollment <- BearhausEnrollmentClean(read_excel(as.list(list.files(paste0(params$path, "/BearhausEnrollment"), 
                                            full.names = TRUE)), combine = TRUE))
dfAll <- dplyr::summarize(group_by(filter(enrollment, `Term Flag` == "Fall"), `Year`), 
                   `Mean Verbal` = mean(`GRE Verbal`, na.rm = TRUE), 
                   `Mean Quantitative` = mean(`GRE Quantitative`, na.rm = TRUE), 
                   Average = (`Mean Verbal` + `Mean Quantitative`) / 2, 
                   `Median Verbal` = median(`GRE Verbal`, na.rm = TRUE), 
                   `Median Quantitative` = median(`GRE Quantitative`, na.rm = TRUE))
dfPhD <- dplyr::summarize(group_by(filter(enrollment, `Term Flag` == "Fall", Degree == "Doctor of Philosophy"), `Year`), 
                   Count = length(Degree),
                   `Mean Verbal` = mean(`GRE Verbal`, na.rm = TRUE), 
                   `Mean Quantitative` = mean(`GRE Quantitative`, na.rm = TRUE), 
                   Average = (`Mean Verbal` + `Mean Quantitative`) / 2, 
                   `Median Verbal` = median(`GRE Verbal`, na.rm = TRUE), 
                   `Median Quantitative` = median(`GRE Quantitative`, na.rm = TRUE))
```

```{r GREPerAllTable}
kable(dfAll)
```

```{r averageGREPerAllPlot}
ggplot(data = dfAll, aes(x = `Year`, y = Average, group = 1)) +
  geom_line() +
  geom_point() +
  theme_bw()
```

```{r GREPerPhDTable}
kable(dfPhD)
```

```{r}
dfPhD <- gather(dfPhD, "Test", "Value", 2:7)
dfPhD$Variable <- "GRE"
dfPhD$Variable[dfPhD$Test == "Count"] <- "Count"
```

```{r GREPerPhDPlot}
ggplot(data = filter(dfPhD, Test %in% c("Mean Verbal", "Mean Quantitative", "Count", 
                                        "Median Verbal", "Median Quantitative")), 
       aes(x = `Year`, y = Value, group = Test, color = Test)) +
  geom_line() +
  geom_point() +
  facet_wrap(~Variable, scales = "free") +
  theme_bw()
```

```{r averageGREPerPhDPlot}
ggplot(data = filter(dfPhD, Test %in% c("Average", "Count")), 
       aes(x = `Year`, y = Value, group = Test, color = Test)) +
  geom_line() +
  geom_point() +
  facet_wrap(~Variable, scales = "free") +
  theme_bw()
```

```{r dataphdsGRECount}
dfPhDGRECount <- dplyr::summarize(group_by(filter(enrollment, !(is.na(`GRE Verbal`)), Degree == "Doctor of Philosophy", `Term Flag` == "Fall"), `Year`, Department),
                                  `Total` = length(Degree),
                                  `X <= 10` = length(Degree[`GRE Quantitative` <= 10 | `GRE Verbal` <= 10]),
                                  `10 < X <= 20` = length(Degree[(`GRE Quantitative` <= 20 & `GRE Quantitative` > 10)]),
                                  `20 < X <= 30` = length(Degree[(`GRE Quantitative` <= 30 & `GRE Quantitative` > 20)]),
                                  `30 < X <= 40` = length(Degree[(`GRE Quantitative` <= 40 & `GRE Quantitative` > 30)]),
                                  `40 < X <= 50` = length(Degree[(`GRE Quantitative` <= 50 & `GRE Quantitative` > 40)]),
                                  `50 < X <= 60` = length(Degree[(`GRE Quantitative` <= 60 & `GRE Quantitative` > 50)]),
                                  `60 < X <= 70` = length(Degree[(`GRE Quantitative` <= 70 & `GRE Quantitative` > 60)]),
                                  `70 < X <= 80` = length(Degree[(`GRE Quantitative` <= 80 & `GRE Quantitative` > 70)]),
                                  `80 < X <= 90` = length(Degree[(`GRE Quantitative` <= 90 & `GRE Quantitative` > 80)]),
                                  `90 < X <= 100` = length(Degree[(`GRE Quantitative` <= 100 & `GRE Quantitative` > 90)]))
dfPhDGRECount <- gather(dfPhDGRECount, "Range", "Count", 3:13)
dfPhDGRECount$Cluster <- "Below"
dfPhDGRECount[dfPhDGRECount$Range %in% c("70 < X <= 80", "80 < X <= 90", "90 < X <= 100"),]$Cluster <- "Above"
dfPhDGRECountdiscrete <- dfPhDGRECount <- dplyr::summarize(group_by(filter(enrollment, !(is.na(`GRE Verbal`)), Degree == "Doctor of Philosophy", `Term Flag` == "Fall"), 
                                                                    `Year`, Department),
                                                           `Total` = length(Degree),
                                                           `X <= 70` = length(Degree[`GRE Quantitative` <= 70]),
                                                           `70 < X` = length(Degree[(`GRE Quantitative` > 70)]))
dfPhDGRECountdiscrete <- gather(dfPhDGRECountdiscrete, "Range", "Count", 3:5)
```

```{r phdsGRECount, fig.width=9, fig.height=30}
ggplot(data = filter(dfPhDGRECountdiscrete, !(Range == "Total")), 
       aes(x = `Year`, y = Count, group = Range, color = Range)) +
  geom_line() +
  geom_point() +
  facet_wrap(~Department, ncol = 2, scales = "free") +
  theme_bw()
```


