---
output: pdf_document
header-includes:
    - \usepackage{pdfpages}
    - \usepackage[pages=some, placement = top, vshift = -100]{background}
    - \usepackage{tikz}
    - \usetikzlibrary{mindmap,shadows}
params: 
  degree: "NULL"
  major: "NULL"
---

```{r, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(xtable.comment = FALSE)
```

```{r, include = FALSE}
inFile <- input$file
      inFile <- inFile[!(str_detect(inFile$name, ".docx")),]
      file.rename(inFile$datapath,
                  paste(inFile$datapath, ".xls", sep=""))
      files <- paste(inFile$datapath, ".xls", sep="") %>% 
        read_clean
      gathered <- files$crystal %>%
        gather("Variable", "Value", 16:26) %>%
        select(DEGR, MAJOR, `Year Term`, ID, YEAR, Variable, Value) %>%
        distinct %>%
        group_by(YEAR, DEGR, MAJOR)
      
      goBaylor <- files$goBaylor %>%
        gather("Go Baylor Code", "Count", 14:16) %>%
        select(BANNER_ID, APPLICATION_ID, PROGRAM, TERM, `Go Baylor Code`, Count) %>%
        distinct

      goBaylor <- goBaylor %>% mutate(YEAR = str_extract(TERM, "[0-9]{4}"))

      goBaylor %<>%
        group_by(YEAR, PROGRAM)
      
      
      maxYear <- if(gathered %>% 
                    filter(YEAR == max(YEAR)) %>% 
                    ungroup %>% 
                    select(`Year Term`) %>% 
                    str_detect(c("Spring", "Fall", "Summer")) %>% 
                    all()){
        max(gathered$YEAR)
      }else{
                       max(gathered$YEAR) - 1
                    }
      
      summaryApps <- gathered %>% 
        filter(YEAR == maxYear) %>% 
        group_by(Variable) %>% 
        summarise(Count = sum(Value, na.rm = TRUE))
      
      flowChartData <- data_frame(Total = summaryApps %>% 
                                    select(Count) %>% 
                                    sum,
                                  Offers = summaryApps %>% 
                                    filter(Variable %in% c("Regular Admission Extended", 
                                                           "Probationary Admission Extended")) %>%
                                    select(Count) %>%
                                    sum,
                                  Rejected = summaryApps %>% 
                                    filter(Variable == "Rejected") %>%
                                    select(Count) %>% 
                                    sum,
                                  Enrolled = summaryApps %>% 
                                    filter(Variable %in% c("Regular Admission Accepted", 
                                                           "Probationary Admission Accepted")) %>%
                                    select(Count) %>%
                                    sum,
                                  Declined = summaryApps %>% 
                                    filter(Variable %in% c("Regular Admission Declined", 
                                                           "Probationary Admission Declined")) %>%
                                    select(Count) %>%
                                    sum) %>%
        mutate(OffersPer = round(Offers / Total * 100),
               RejectedPer = round(Rejected / Total * 100),
               EnrolledPer = round(Enrolled / Offers * 100),
               DeclinedPer = round(Declined / Offers * 100))
      
```

# `r params$degree` `r params$major` Numbers
```{r, include = FALSE}
gathered <- gathered %>% filter(DEGR == params$degree, MAJOR == params$major)
```

```{r, child = 'applications.Rmd'}
```

```{r, child = 'offerRejectionCancelled.Rmd'}
```

```{r, child = 'acceptedDeclined.Rmd'}
```

````{r, include = FALSE}
if(is.null(input$fileADDProgram)){
      files <- NULL
    }else{
inFile <- input$fileADDProgram
files <- inFile$name
path <- inFile$datapath
filter <- files %>% ldply(function(file){
  file %>% str_detect(params$major)
})
path <- path[filter$V1]
files <- files[filter$V1]
file.copy(path, paste0("temp/All/program/", files))
    }

evalcheck <- if(is.null(files)){
  FALSE
}else{
    ncol(files) > 0
}
```

```{r, eval = evalcheck, results = 'asis'}
  files %>% l_ply(function(file){  
     cat('\\includepdf[pages = -]{', 'temp/All/program', file, '}', sep = "")
    cat('')
   })
```

