---
title: "Application Report"
author: "Baylor Graduate School"
output: pdf_document
params: 
  Report:
    label: "Report Type:"
    value: Graduate School
    input: select
    choices: [Graduate School, Program]
  Major:
    label: "Major:"
    value: 
    input: select
    choices: [EDC, BIO, BMS, CHE, CMUS, CUTE, EDP, EEES, ELC, ENG, GEO, HESL, HIS, IS, KENH, MECH, MTH, PHI, PHY, PSC, PSY, REL, SOC, STAT, CPSY, NMID, NUPR, OCTH, EM, ORCL, SURG, ORTH, SPSY, AMS, CMTN, COM, CSD, INTR, JOU, MST, SPA, THEA, ACC, BUAD, EMBA, OMBA, EGR, DIR, HCA, INTJ, COMP, COND, COPI, MUED, MUHL, MUTH, PERF, PPP, CHED, PPA, CSI, EBIO, ENSC, NUTR, BME, ECO, EDA, HESA, HHPR, ONLI, TAX, NMJ, SWO, ENV, EP, SPPE, SMGT, ENT, HESR, PT, NUTN]
    multiple: FALSE
  Degree:
    label: "Degree:"
    value: 
    input: select
    choices: [EDD, PHD, PSYD, DNP, DSCOT, DSCPA, DSCPT, ES, MA, MACC, MBA, ME, MFA, MHA, MIJ, MM, MPH, MPP, MS, MSBME, MSCD, MSECE, MSECO, MSED, MSIS, MSME, MSN, MTA, NDG, DMA, MES, DPT]
  Year:
    label: "Year:"
    value: All
    input: select
    choices: [All, 2014, 2015, 2016]
    multiple: FALSE
  Data: 
    label: "Input dataset:"
    value: Application.xlsx
    input: file
---

```{r, include = FALSE, eval = TRUE}
knitr::opts_chunk$set(echo = FALSE, eval = FALSE)
options(xtable.comment = FALSE)
invisiblePackage(c("xtable", "plyr", "tidyr", "readxl", "ggplot2", "magrittr", "dplyr"))


Programs <- params$Program
Years <- params$Year
Data_tables <- read_excel(params$Data)
Data_graphs <- read_excel(params$Data) %>%
  gather("Application Count", Count, 5:13) 
if(any(Programs == "All")){Programs <- unique(Data_tables$Program)}
if(any(Years == "All")){Years <- unique(Data_tables$Year)}
```

```{r, eval = TRUE}
invisible(llply(llply(Programs, function(Programs, Data, Years){
  Data %>% filter(Program == Programs) %>%
  filter(!(`Application Count` == "Change of App (MA to MSCD)")) %>%
  mutate(`Application Count` = factor(`Application Count`, levels = c("Total Apps", "Total Offers Extended", "Accepted BU Offer", "Declined BU Offer", "No Decision for Applicant", "Total Declined", "Total Cancelled", "No Decision Entered by Program"))) %>%
    ggplot(aes(x = Year, y = Count, color = `Application Count`)) +
    geom_line() +
    scale_x_continuous(breaks = Years) +
    theme_bw() +
    ggtitle(paste("Application Counts", Programs))}, Data = Data_graphs, Years = Years), print))
```

```{r, results = 'asis', eval = TRUE}
invisible(llply(llply(Programs, function(Programs, Data, Years){
  Data %<>% filter(Program == Programs) %>%
  select(-`Change of App (MA to MSCD)`, -Program, -Degree, -School) %>%
  t %>% `[`(-1,) %>% as.data.frame 
  names(Data) <- Years
  Data %>% xtable(caption = paste("Application Counts", Programs), digits = 0)}, Data = Data_tables, Years = Years), function(x){print(x)}))
```

```{r}
invisible(llply(llply(Programs, function(Programs, Data, Years){
  Data %>% 
    filter(Program == Programs, `Application Count` == "Total Apps") %>%
    ggplot(aes(x = Year, y = Count, color = `Application Count`)) +
    geom_line() +
    scale_x_continuous(breaks = Years) +
    theme_bw() +
    theme(legend.position = "none") +
    ggtitle(paste("Total Applications", Programs))}, Data = Data_graphs, Years = Years), print))
```

```{r}
invisible(llply(llply(Programs, function(Programs, Data, Years){
  Data %>% 
    filter(Program == Programs, `Application Count` == "Total Offers Extended") %>%
    ggplot(aes(x = Year, y = Count, color = `Application Count`)) +
    geom_line() +
    scale_x_continuous(breaks = Years) +
    theme_bw() +
    theme(legend.position = "none") +
    ggtitle(paste("Total Offers Extended", Programs))}, Data = Data_graphs, Years = Years), print))
```

```{r}
invisible(llply(llply(Programs, function(Programs, Data, Years){
  Data %>% 
    filter(Program == Programs, `Application Count` == "Accepted BU Offer") %>%
    ggplot(aes(x = Year, y = Count, color = `Application Count`)) +
    geom_line() +
    scale_x_continuous(breaks = Years) +
    theme_bw() +
    theme(legend.position = "none") +
    ggtitle(paste("Accepted BU Offer", Programs))}, Data = Data_graphs, Years = Years), print))
```

```{r}
invisible(llply(llply(Programs, function(Programs, Data, Years){
  Data %>% 
    filter(Program == Programs, `Application Count` == "Declined BU Offer") %>%
    ggplot(aes(x = Year, y = Count, color = `Application Count`)) +
    geom_line() +
    scale_x_continuous(breaks = Years) +
    theme_bw() +
    theme(legend.position = "none") +
    ggtitle(paste("Declined BU Offer", Programs))}, Data = Data_graphs, Years = Years), print))
```

```{r}
invisible(llply(llply(Programs, function(Programs, Data, Years){
  Data %>% 
    filter(Program == Programs, `Application Count` == "No Decision for Applicant") %>%
    ggplot(aes(x = Year, y = Count, color = `Application Count`)) +
    geom_line() +
    scale_x_continuous(breaks = Years) +
    theme_bw() +
    theme(legend.position = "none") +
    ggtitle(paste("No Decision for Applicant", Programs))}, Data = Data_graphs, Years = Years), print))
```

```{r}
invisible(llply(llply(Programs, function(Programs, Data, Years){
  Data %>% 
    filter(Program == Programs, `Application Count` == "Total Declined") %>%
    ggplot(aes(x = Year, y = Count, color = `Application Count`)) +
    geom_line() +
    scale_x_continuous(breaks = Years) +
    theme_bw() +
    theme(legend.position = "none") +
    ggtitle(paste("Total Declined", Programs))}, Data = Data_graphs, Years = Years), print))
```

```{r}
invisible(llply(llply(Programs, function(Programs, Data, Years){
  Data %>% 
    filter(Program == Programs, `Application Count` == "Total Cancelled") %>%
    ggplot(aes(x = Year, y = Count, color = `Application Count`)) +
    geom_line() +
    scale_x_continuous(breaks = Years) +
    theme_bw() +
    theme(legend.position = "none") +
    ggtitle(paste("Total Cancelled", Programs))}, Data = Data_graphs, Years = Years), print))
```

```{r}
invisible(llply(llply(Programs, function(Programs, Data, Years){
  Data %>% 
    filter(Program == Programs, `Application Count` == "No Decision Entered by Program") %>%
    ggplot(aes(x = Year, y = Count, color = `Application Count`)) +
    geom_line() +
    scale_x_continuous(breaks = Years) +
    theme_bw() +
    theme(legend.position = "none") +
    ggtitle(paste("No Decision Entered by Program", Programs))}, Data = Data_graphs, Years = Years), print))
```
