#' Simulate Bearhaus Enrollment Data
#'
#' @param n number of students
#' @param ... other options
#'
#' @return data frame of simulated Bearhaus Enrollment Data
#' @export 
#' 
#' @importFrom dplyr data_frame
#'
simEnrollment <- function(n, ...){
  n
  data_frame("Assessment Group" = rnorm(1), 
             "Concentration 1" = rnorm(1), 
             "Concentration 2" = rnorm(1), 
             "Citizenship Nation" = rnorm(1), 
             "Classification" = rnorm(1), 
             "App Term1" = rnorm(1), 
             "College" = rnorm(1), 
             "Semester Hours" = rnorm(1), 
             "Degree" = rnorm(1), 
             "Department" = rnorm(1), 
             "End CUM GR Earned Hours" = rnorm(1),
             "End CUM GR GPA" = rnorm(1), 
             "Enrollment Count" = rnorm(1), 
             "Ethnicity" = rnorm(1), 
             "International Status" = rnorm(1), 
             "Full-Time/Part-Time Status" = rnorm(1), 
             "Gender" = rnorm(1),
             "GMAT Groups" = rnorm(1), 
             "GMAT Quantitative" = rnorm(1),
             "GMAT Total" = rnorm(1), 
             "GMAT Verbal" = rnorm(1), 
             "GRE Writing" = rnorm(1), 
             "Major Count" = rnorm(1), 
             "Major Flag" = rnorm(1), 
             "Major" = rnorm(1), 
             "Minor" = rnorm(1), 
             "Minority Status" = rnorm(1), 
             "Name" = rnorm(1), 
             "New Student Flag" = rnorm(1), 
             "PIDM" = rnorm(1), 
             "Program Count" = rnorm(1), 
             "Program Flag" = rnorm(1), 
             "Program" = rnorm(1),
             "Religion" = rnorm(1), 
             "Student ID" = rnorm(1), 
             "Term" = rnorm(1), 
             "Term Flag" = rnorm(1),
             "TOEFL (Computer)" = rnorm(1),
             "TOEFL (Paper)" = rnorm(1), 
             "Academic Unit" = rnorm(1), 
             "Year" = rnorm(1), 
             "eth_his" = rnorm(1),
             "eth_asian" = rnorm(1), 
             "eth_black" = rnorm(1), 
             "eth_amerind" = rnorm(1),
             "eth_white" = rnorm(1), 
             "eth_pacisle" = rnorm(1),
             "BeginningCUM GR Earned Hours" = rnorm(1),
             "Beginning CUM Graduate GPA" = rnorm(1), 
             "First Generation College Student" = rnorm(1),
             "End of Term Status" = rnorm(1), 
             "Citizenship Flag" = rnorm(1), 
             "Quarter Hours" = rnorm(1), 
             "SGBSTDN_EGOL_CODE" = rnorm(1), 
             "GMAT Writing" = rnorm(1),
             "HONORS_FLAG" = rnorm(1), 
             "Level" = rnorm(1),
             "Provisional Admit" = rnorm(1), 
             "DateTime Stamp of when row was loaded" = rnorm(1), 
             "SORPCOL_SBGI_CODE" = rnorm(1),
             "SHRTGPA_GPA" = rnorm(1), 
             "GRE Quan Percent" = rnorm(1),
             "GRE Quant REV Percent" = rnorm(1), 
             "GRE Verbal Percent" = rnorm(1), 
             "GRE_Verbal_REV_Percent" = rnorm(1), 
             "GRE Writing Percent" = rnorm(1), 
             "GRE HI Verbal" = rnorm(1), 
             "GRE HI Quantitative" = rnorm(1),
             "NU_Entry_term" = rnorm(1),
             "NU_Level" = rnorm(1), 
             "NU_status" = rnorm(1), 
             "GMAT_QUANTITATIVE_PCT" = rnorm(1),
             "GMAT_REASONING_PCT" = rnorm(1),
             "GMAT_TOTAL_PCT" = rnorm(1), 
             "GMAT_VERBAL_PCT" = rnorm(1),
             "GMAT_WRITING_PCT" = rnorm(1), 
             "IELTS_Listening" = rnorm(1), 
             "IELTS_Reading" = rnorm(1), 
             "IELTS_Speaking" = rnorm(1), 
             "IELTS_Writing" = rnorm(1), 
             "PEARSON_COMM_SKILLS_LISTENING" = rnorm(1), 
             "PEARSON_COMM_SKILLS_READING" = rnorm(1), 
             "PEARSON_COMM_SKILLS_SPEAKING" = rnorm(1), 
             "PEARSON_COMM_SKILLS_WRITING" = rnorm(1),
             "PEARSON_ENB_SKILLS_GRAMMER" = rnorm(1), 
             "PEARSON_ENB_SKILLS_ORAL_FLUENCY" = rnorm(1),
             "PEARSON_ENB_SKILLS_PRONNUCIATION" = rnorm(1), 
             "PEARSON_ENB_SKILLS_SPELLING" = rnorm(1), 
             "PEARSON_ENB_SKILLS_VOCABULARY" = rnorm(1), 
             "PEARSON_SKILLS_WRITTEN_DISCOURSE" = rnorm(1),
             "TOEFL_LISTENING" = rnorm(1), 
             "TOEFL_SPEAKING" = rnorm(1), 
             "TOEFL_READING" = rnorm(1), 
             "TOEFL_WRITING" = rnorm(1), 
             "toefl_total_internet" = rnorm(1), 
             "PEARSON_ENB_SKILLS_PRONUNCIATION" = rnorm(1), 
             "BEG_CUM_INST_HRS_GR" = rnorm(1), 
             "BEG_CUM_TRANSFER_HRS_GR" = rnorm(1), 
             "GMAT_REASONING" = rnorm(1), 
             "Age" = rnorm(1), 
             "site" = rnorm(1))
}